export const programs = [
 {id:'waterloo',university:'University of Waterloo',name:'Computer Science',short:'Waterloo CS',city:'Waterloo, ON',field:'Computer Science',mark:'W',colour:'#edc949',base:22,coop:true,required:['ENG4U','MHF4U','MCV4U'],description:'Explore computing, algorithms and software through a flexible degree with opportunities to gain hands-on experience.'},
 {id:'uoft',university:'University of Toronto',name:'Computer Science',short:'U of T CS',city:'Toronto, ON',field:'Computer Science',mark:'U of T',colour:'#143967',base:28,coop:false,required:['ENG4U','MCV4U'],description:'Study the foundations of computing in Toronto, with pathways into software, artificial intelligence and research.'},
 {id:'mcmaster',university:'McMaster University',name:'Computer Science',short:'McMaster CS',city:'Hamilton, ON',field:'Computer Science',mark:'M',colour:'#7e1734',base:54,coop:true,required:['ENG4U','MHF4U','MCV4U'],description:'Combine computational theory with practical programming and collaborative projects in a close-knit learning environment.'},
 {id:'western',university:'Western University',name:'Computer Science',short:'Western CS',city:'London, ON',field:'Computer Science',mark:'W',colour:'#573183',base:61,coop:true,required:['ENG4U','MCV4U'],description:'Build a foundation in computer science and explore software engineering, data and interactive technologies.'},
 {id:'tmu',university:'Toronto Metropolitan University',name:'Computer Science',short:'TMU CS',city:'Toronto, ON',field:'Computer Science',mark:'TMU',colour:'#146da3',base:78,coop:true,required:['ENG4U','MHF4U','MCV4U'],description:'Develop practical computing skills in downtown Toronto and explore professional experience through co-op opportunities.'},
 {id:'york',university:'York University',name:'Computer Science',short:'York CS',city:'Toronto, ON',field:'Computer Science',mark:'Y',colour:'#db3350',base:84,coop:true,required:['ENG4U','MHF4U','MCV4U'],description:'Explore computing at the Lassonde School with opportunities in software development and emerging technology.'},
 {id:'ocad',university:'OCAD University',name:'Digital Futures',short:'OCAD Digital Futures',city:'Toronto, ON',field:'Design',mark:'OCAD',colour:'#393939',base:75,coop:false,required:['ENG4U'],description:'Bring design and technology together through creative projects, interactive experiences and digital media.'},
 {id:'ottawa',university:'University of Ottawa',name:'Computer Science',short:'uOttawa CS',city:'Ottawa, ON',field:'Computer Science',mark:'uO',colour:'#8b183d',base:81,coop:true,required:['ENG4U','MHF4U','MCV4U'],description:'Explore software, computing and data in Canada’s capital, with opportunities for work experience.'},
 {id:'queens',university:'Queen’s University',name:'Commerce',short:'Queen’s Commerce',city:'Kingston, ON',field:'Business',mark:'Q',colour:'#b18c36',base:40,coop:false,required:['ENG4U','MCV4U'],description:'Explore business strategy, finance, marketing and leadership through a broad commerce experience.'},
 {id:'guelph',university:'University of Guelph',name:'Software Engineering',short:'Guelph Software Eng.',city:'Guelph, ON',field:'Engineering',mark:'G',colour:'#bf3137',base:72,coop:true,required:['ENG4U','MHF4U','MCV4U'],description:'Learn to design and develop reliable software through a combination of computing and team-based practice.'}
];
export const initialState = {version:1,profile:{name:'Maya Chen',grade:'12',school:'Northview Secondary School',city:'Toronto',bio:'Robotics club, student council, and designing useful things.',interests:['Computer Science','UX / Design','AI','Business'],coop:true,move:true},courses:[{id:'eng',code:'ENG4U',name:'English',grade:92,status:'Completed'},{id:'mhf',code:'MHF4U',name:'Advanced Functions',grade:95,status:'Completed'},{id:'mcv',code:'MCV4U',name:'Calculus and Vectors',grade:91,status:'In progress'},{id:'ics',code:'ICS4U',name:'Computer Science',grade:96,status:'In progress'},{id:'sch',code:'SCH4U',name:'Chemistry',grade:88,status:'In progress'},{id:'bbb',code:'BBB4M',name:'International Business',grade:92,status:'In progress'}],saved:['waterloo','uoft','mcmaster','western','tmu','york'],applications:[{programId:'waterloo',status:'In progress',tasks:[true,false,false],notes:'Draft ideas for my supplementary application.'},{programId:'uoft',status:'Submitted',tasks:[true,true,true],notes:''},{programId:'mcmaster',status:'Not started',tasks:[false,false,false],notes:''}],deadlines:[{id:'ouac',title:'OUAC Application Deadline',subtitle:'All programs',date:'2027-05-29',done:false,label:'To do'},{id:'aif',title:'Waterloo AIF & SE Deadline',subtitle:'Waterloo CS',date:'2027-06-07',done:false,label:'To do'},{id:'supp',title:'U of T Supplementary Application',subtitle:'Social Sciences',date:'2027-06-15',done:true,label:'Complete'},{id:'mac',title:'McMaster Application',subtitle:'Computer Science',date:'2027-06-25',done:false,label:'Pending'}]};
export function average(courses){const grades=courses.filter(c=>c.grade!==''&&Number.isFinite(Number(c.grade))&&/4[UM]$/i.test(c.code)).map(c=>Number(c.grade)).sort((a,b)=>b-a).slice(0,6);return grades.length?grades.reduce((a,b)=>a+b,0)/grades.length:0;}
export function chance(p,avg){return Math.max(1,Math.min(97,Math.round(p.base+(avg-average(initialState.courses))*3)));}
export function category(n){return n<40?'Reach':n<70?'Target':'Likely';}
export function reply(question,data){const q=question.toLowerCase(),avg=average(data.courses),saved=programs.filter(p=>data.saved.includes(p.id));const warning=' These are illustrative demo scores, not real admission predictions.';
 if(/95|calculus|what.if/.test(q)){const adjusted=data.courses.map(c=>c.code==='MCV4U'?{...c,grade:95}:c),next=average(adjusted);return `If your Calculus grade were 95%, your Top 6 average would be ${next.toFixed(1)}%, compared with ${avg.toFixed(1)}% now. In this demo, Waterloo CS would show ${chance(programs[0],next)}%. You can try other grades in the Ontario Grade Calculator.${warning}`;}
 if(/waterloo|strengthen|activity|extracurricular/.test(q))return 'For a Waterloo CS application, reflect on projects you have built, problems you have solved, teamwork and what you learned from those experiences. Practise explaining your contribution clearly. Check Waterloo’s official instructions for required supplementary materials. This demo cannot evaluate or predict a real admissions decision.';
 if(/safety|balance|shortlist|likely/.test(q)){const likely=saved.filter(p=>category(chance(p,avg))==='Likely').length;return `You have ${saved.length} saved programs, including ${likely} in the demo’s Likely category. ${likely>=2?'Your shortlist already includes a couple of lower-risk options.':'Consider adding a couple of programs with a broader range of entry expectations.'} Think about cost, location and whether you would enjoy attending each one.${warning}`;}
 if(/requirement|course|prerequisite/.test(q)){const missing=['ENG4U','MHF4U','MCV4U'].filter(code=>!data.courses.some(c=>c.code===code));return `The sample CS programs commonly list ENG4U, MHF4U and MCV4U. ${missing.length?'Your plan is missing: '+missing.join(', ')+'.':'All three are in your course plan.'} Actual requirements and how averages are calculated differ by university. Verify each program’s current official requirements.`;}
 if(/deadline|when|date/.test(q)){const next=[...data.deadlines].filter(d=>!d.done).sort((a,b)=>a.date.localeCompare(b.date))[0];return next?`Your first incomplete tracked deadline is ${next.title} on ${next.date}. You have ${data.deadlines.filter(d=>!d.done).length} deadlines still to complete. The initial dates are fictional samples; replace them with verified dates on the Deadlines page.`:'All your tracked deadlines are complete. Add another on the Deadlines page if needed.';}
 if(/chance|average|grade/.test(q))return `Your current Top 6 average is ${avg.toFixed(1)}%. Editing your grades updates the demo scores on your shortlist. A grade average alone does not capture real admissions decisions, which can also depend on program rules, applicant pools and supplementary materials.${warning}`;
 if(/application|apply|submit/.test(q))return `You are tracking ${data.applications.length} applications. Open Applications to change a status, check off tasks and add notes. This tracker does not submit anything to a university or OUAC.`;
 return 'I can demonstrate answers about your grades, course requirements, application balance and tracked deadlines. Try “What happens if I get 95 in Calculus?” or “What are my next deadlines?” This prototype uses scripted replies; live AI can be connected later.';
}
